/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mushfika
 */
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class MemberInfo extends javax.swing.JFrame {

    /**
     * Creates new form MemberInfo
     */
Connection conn=null;
ResultSet rs = null;
PreparedStatement pst = null;

    public MemberInfo() {
        initComponents();
          conn=Connect.ConnectDB();
          Create_Table();
    }
   public void  Update_Table()
    {
        
        try{
            
            String sql="select * from Member where MemberId LIKE ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,search_txt.getText());
            rs=pst.executeQuery();
            table_member.setModel(DbUtils.resultSetToTableModel(rs));
            
            search_txt.setText(null);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void Create_Table()
    {
        
        try{
            String sql="select * from Member";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_member.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
             
            try{
                rs.close();
                pst.close();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        search_txt = new javax.swing.JTextField();
        Button_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_member = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        text_member = new javax.swing.JTextField();
        text_name = new javax.swing.JTextField();
        text_con = new javax.swing.JTextField();
        text_dept = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        Button_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Button_search.setForeground(new java.awt.Color(102, 0, 0));
        Button_search.setText("SEARCH");
        Button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Member ID ");

        table_member.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        table_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MemberId", "MemberName", "Dept", "ContactNo"
            }
        ));
        table_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_memberMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_memberMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_member);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("SEARCH");

        button_save.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        button_save.setForeground(new java.awt.Color(51, 0, 0));
        button_save.setText("SAVE");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        button_delete.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        button_delete.setForeground(new java.awt.Color(51, 0, 0));
        button_delete.setText("DELETE");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_update.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        button_update.setForeground(new java.awt.Color(51, 0, 0));
        button_update.setText("UPDATE");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Member Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Department");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Contact Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Button_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_member)
                            .addComponent(text_name)
                            .addComponent(text_con, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_dept, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_update)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_search))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(text_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_save)
                            .addComponent(button_delete)
                            .addComponent(button_update))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_memberMouseClicked
        
          try{
            
            int row=table_member.getSelectedRow();
            String Table_Click=(table_member.getModel().getValueAt(row, 0).toString());
            String sql="select  * from Member where MemberId =' " +Table_Click+ " ' " ;
            pst=conn.prepareStatement("select  * from Member where Dept =' " +Table_Click+ " ' " );
           rs=pst.executeQuery();
          // boolean tr=rs.next();
            
            if(rs.next())
            {
                String add1=rs.getString("MemberId");
                text_member.setText(add1);
                 String add2=rs.getString("MemberName");
                text_name.setText(add2);
                String add3=rs.getString("Dept");
                text_dept.setText(add3);
                 String add4=rs.getString("ContactNo");
                text_con.setText(add4);
               JOptionPane.showMessageDialog(null,"no items");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_memberMouseClicked

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        
        try{
            String sql="Insert into Member(MemberId,MemberName,Dept,ContactNo)values(?,?,?,?)";
            pst=conn.prepareStatement(sql);
            
            pst.setString(1,text_member.getText());
             pst.setString(2,text_name.getText());
              pst.setString(3,text_dept.getText());
               pst.setString(4,text_con.getText());
               
               pst.execute();
               
                text_member.setText(null);
            text_name.setText(null);
            text_dept.setText(null);
            text_con.setText(null);
            JOptionPane.showMessageDialog(null,"Saved");
            
        }
        catch(Exception e)
        {
            text_member.setText(null);
            text_name.setText(null);
            text_dept.setText(null);
            text_con.setText(null);
            JOptionPane.showMessageDialog(null,e);
        }
        Create_Table();
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        
        String sql="Delete from Member where MemberId=?";
        
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,text_member.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Deleted");
            
             text_member.setText(null);
            text_name.setText(null);
            text_dept.setText(null);
            text_con.setText(null);
        }
        catch(Exception e)
        {
             text_member.setText(null);
            text_name.setText(null);
            text_dept.setText(null);
            text_con.setText(null);
            JOptionPane.showMessageDialog(null, e);
        }
        Create_Table();
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        
        
        try{
            
            String Value1=text_member.getText();
            String Value2=text_name.getText();
            String Value3=text_dept.getText();
            String Value4=text_con.getText();
            
            String sql="update Member set ContactNo= ' " +Value4+" ' where MemberId= ' "+Value1+" ' ";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Updated");
            
        }
        catch(Exception e)
        {
             text_member.setText(null);
            text_name.setText(null);
            text_dept.setText(null);
            text_con.setText(null);
            JOptionPane.showMessageDialog(null, e);
        }
        Create_Table();
    }//GEN-LAST:event_button_updateActionPerformed

    private void Button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_searchActionPerformed
        
        try{
            
            String sql="select * from Member where MemberId=?";
               pst=conn.prepareStatement(sql);
              pst.setString(1,search_txt.getText());
              rs=pst.executeQuery();
              
              if(rs.next())
              {
                /*   String add1=rs.getString("MemberId");
                text_member.setText(add1);
                 String add2=rs.getString("MemberName");
                text_name.setText(add2);
                String add3=rs.getString("Dept");
                text_dept.setText(add3);
                 String add4=rs.getString("ContactNo");
                text_con.setText(add4);*/
                Update_Table();
              }
              search_txt.setText(null);
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_Button_searchActionPerformed

    private void table_memberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_memberMousePressed
        // TODO add your handling code here:
     /*    try{
            
            int row=table_member.getSelectedRow();
            String Table_Click=(table_member.getModel().getValueAt(row, 0).toString());
            System.out.print(Table_Click);
            String sql="select * from Member where MemberId=' " +Table_Click+ " ' " ;
            pst=conn.prepareStatement(sql);
            pst.execute();
           rs=pst.executeQuery();
            
            if(rs.next())
            {
                String add1=rs.getString("MemberId");
                text_member.setText(add1);
                 String add2=rs.getString("MemberName");
                text_name.setText(add2);
                String add3=rs.getString("Dept");
                text_dept.setText(add3);
                 String add4=rs.getString("ContactNo");
                text_con.setText(add4);
               // JOptionPane.showMessageDialog(null,"no items");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }*/
        
    }//GEN-LAST:event_table_memberMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_search;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField search_txt;
    private javax.swing.JTable table_member;
    private javax.swing.JTextField text_con;
    private javax.swing.JTextField text_dept;
    private javax.swing.JTextField text_member;
    private javax.swing.JTextField text_name;
    // End of variables declaration//GEN-END:variables
}
